services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $cachePrefixSeed: "%cache_prefix_seed%"

    Doctrine\Migrations\Finder\MigrationFinder:
        class: Doctrine\Migrations\Finder\RecursiveRegexFinder
